#!/bin/env bash

# --------------------------------------------------------

# shellcheck source=/dev/null
. "$WORKDIR"/modules/colors
# shellcheck source=/dev/null
. "$WORKDIR"/modules/common

# --------------------------------------------------------

command_to_handle_path="$1"
shift
if [ -z "$command_to_handle_path" ]; then
    error "No command provided" "Need to provide a command to handle"
    exit 1
fi

command_file_to_handle="$WORKDIR/commands/$command_to_handle_path"
if [ ! -f "$command_file_to_handle" ]; then
    error "Command not found" "Command '$command_to_handle_path' not found"
    exit 1
fi

# --------------------------------------------------------

# shellcheck source=/dev/null
source "$WORKDIR/commands/$command_to_handle_path"

# load the interface
source "$WORKDIR/modules/command_interface"
