#!/bin/env bash

set -e # fail fast
set -u # fail on unset variables
set -o pipefail # fail on pipe errors

# --------------------------------------------------------


CLI_TITLE='IvoryTusk CLI'
CLI_PURPOSE="Manage the envs of laravel like laragon but with just an a CLI"

CLI_NAME_COMMAND="basename \$0"
CLI_VERSION_COMMAND="cat \$WORKDIR/VERSION"
# --------------------------------------------------------

WORKDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
export WORKDIR

# --------------------------------------------------------

. "$WORKDIR"/modules/dependencies
. "$WORKDIR"/modules/common
. "$WORKDIR"/modules/colors
. "$WORKDIR"/modules/resolver

CLI_NAME=$(eval "$CLI_NAME_COMMAND")
CLI_VERSION=$(eval "$CLI_VERSION_COMMAND")

# --------------------------------------------------------

cli_help() {
    title "$CLI_TITLE - ${GREEN}$CLI_NAME${RESET} - $CLI_VERSION"
    subtitle "${ITALIC}$CLI_PURPOSE"
    nl
    show_param_title "Usage:" "$CLI_NAME [command] [options]"
    show_commands_help
}

# --------------------------------------------------------

# catch help
if [ "$#" -eq 0 ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    cli_help
    [ "$#" -eq 0 ] && exit 1
    exit 0
fi

# catch other commands
input_command="$1"
shift
handle_command "$input_command" "$@"

# --------------------------------------------------------


